favicon: https://blades.ninja/favicon.ico
styles:
  - https://cdn.jsdelivr.net/npm/@anyblades/blades@2/css/blades.css?min=0
  - https://cdn.jsdelivr.net/npm/@anyblades/blades@2/css/blades.ninja.css?min=0
